name: run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare build
      run: mkdir -p build && cd build && cmake ..
    - name: make
      run: make
      working-directory: build
    - name: tests
      run: ./tests
      working-directory: build
